language: objective-c
script: xcodebuild -workspace SwiftImageCarousel.xcworkspace -scheme SwiftImageCarousel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
xcodebuild test -workspace SwiftImageCarousel.xcworkspace -scheme SwiftImageCarousel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
