language: objective-c
osx_image: xcode8.3

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:  
  - gem install xcpretty -N
script:  
  - xcodebuild -project SwiftImageCarousel.xcodeproj -scheme SwiftImageCarousel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
   - xcodebuild clean -project SwiftImageCarousel.xcodeproj -scheme SwiftImageCarousel | xcpretty
   - xcodebuild test -project SwiftImageCarousel.xcodeproj -scheme SwiftImageCarousel | xcpretty -s


