language: objective-c
osx_image: xcode8.3
script: 
- xcodebuild clean build -project SwiftImageCarousel.xcodeproj -scheme SwiftImageCarousel CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -quiet
- xcodebuild test -project SwiftImageCarousel.xcodeproj -scheme SwiftImageCarouselTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES -quiet
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios
